### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by 4dvn** [JinZiRong/Simple_Bluetooth_electronic_piano#1]
Can you upload the schematic and image of this midi?

**Comment by JinZiRong** [comment]
Sorry to reply to you so late, since the hardware part of the project was soldered by hand, there is no standard wiring diagram. Also, I think the most critical part is the software program rather than the hardware, because the effects of the routing difference can be eliminated by changing the pin settings.

**Comment by JinZiRong** [comment]
> Can you upload the schematic and image of this midi?

Sorry to reply to you so late. Since the hardware part of the project was soldered by hand, there is no standard wiring diagram. Anymore, I think the most critical part is the software program rather than the hardware, as the effects of the routing difference can be eliminated by changing the pin settings.

**Comment by JinZiRong** [comment]
> Can you upload the schematic and image of this midi?

The simple example critical circuit diagram has been shown in the "蜂鸣器部分原理图".
